### ISSUE TITLE
Why forgot about Russian?

### ISSUE THREAD

**Issue by AbraXabra** [carlenlund/techna-sans#2] opened 2019-06-26 08:36 UTC
Good day!
Why forgot about Russian?
Or politics and then left its mark?

**Comment by carlenlund** [comment] 2019-06-26 10:05
Thanks for the suggestion! I have added Russian to my todo list.

Closing this as duplicate of #1

**Closed as completed** 2019-06-26 10:07 UTC

**Comment by rellikmil** [comment] 2019-06-26 10:22
Ahah, besides me, someone else in Russia needs this font.
Never mind, I am ashamed of him.
P. S. don`t forget about Helmet font :)
